### PR TITLE
Add Travis CI

### PR DESCRIPTION
**Pull request by richelbilderbeek**
I've added a Travis CI config file and a build status button.

Travis CI is a Continuous Integration (hence the name) service. With it, you can trigger a script (`.travis.yml`) that checks -after a Pull Request or commit- if the build is still passing. For me, having a build badge is an indicator of high quality software. The reason I've added is, is to see how I needed to install `make4ht`. There are many more reasons Travis CI is A Good Think (see e.g [a CppCast episode](http://cppcast.com/2017/06/richel-bilderbeek/) or [a Simplify C++ article](https://arne-mertz.de/2017/04/continuous-integration-travis-ci/) by me)

To make this work nicely as I did, you'll need to create a Travis CI account (can sign in with GitHub) and activate this reposity. Also replace `richelbilderbeek` in `README.md` by `michal-h21`. I'll be happy to help you get it working, but it works so simple with GitHub, I do not expect any problems.

I hope you like it. I sure do.

### CODE REVIEW

**Comment by richelbilderbeek** [comment]
Note I removed the status button. It appears to be used in some document generation.

**Comment by michal-h21** [comment]
Thanks a lot for this. `README.md` is indeed used for the documentation, it is converted to LaTeX using Pandoc. Stuff that isn't useful in the PDF, such as the build status icon can be ignored using LaTeX comment: `%`. It seems to work nicely. Thanks again.

**Comment by richelbilderbeek** [comment]
Happy to help making FOSS software even better! 

I am now working on doing the same for [tex4ebook](https://github.com/michal-h21/tex4ebook), but I do have [an Issue](https://github.com/michal-h21/tex4ebook/issues/37) that I've posted there.

**Comment by michal-h21** [comment]
Thanks again. I tried to run tests in Travis, but it fails, because it cannot find [Busted](https://github.com/Olivine-Labs/busted), which can be installed using Luarocks.

**Pull request merged**
