### PR TITLE
Rsekman builddir

### PR DESCRIPTION
**Pull request by michal-h21**
Hi Robin,

thanks for the pull request. I've fixed few things, but the build dir doesn't work at the moment. LaTeX says that it cannot write to the log file. So it clearly needs more fixes.

Best,
Michal

### CODE REVIEW

**Comment by rsekman** [comment]
Hi Michal, thanks for looking at this so quickly. I've been building html to test the code and didn't run into that problem, even when the build dir didn't exist before. Did you fix it or do you have steps to reproduce?

By the way, you should be able to push to [my branch](https://github.com/rsekman/make4ht/tree/builddir). I only saw this PR by accident so I almost missed your contributions. I'll merge your changes into my branch now.

**Comment by michal-h21** [comment]
@rsekman  OK, so I probably do something wrong, but the newest commits are here :)

**Comment by michal-h21** [comment]
@rsekman I think I fixed rest of the stuff, especially the ODT output support and the `clean` mode.

**Comment by rsekman** [comment]
@michal-h21 Sorry for not getting around to look at this until now, but looks great. Thanks a lot!

**Pull request merged**
